
name: Basic Build Workflow

on:
  - pull_request
  - push

jobs:
  build-noetic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ros:noetic
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install Prerequisites
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        apt-get update && rosdep update; \
        rosdep install --from-paths src --ignore-src -y'
    - name: Run Tests
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        catkin_make run_tests; \
        catkin_test_results --verbose'
