---
name: Build & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        container:
          - image: 'ros:noetic'
            env:
              PYTHON_VERSION: 3
              ROS_DISTRO: noetic

    container: ${{ matrix.container }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/${{ github.workspace }}

      - name: Remove broken apt repos [Ubuntu]
        run: |
          for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done
      - name: Install ROS package dependencies
        run: |
          sudo apt update
          sudo apt install -y git
          sudo apt install -y python$PYTHON_VERSION-pip
          sudo apt install -y python3-pip
          sudo apt install -y python$PYTHON_VERSION-osrf-pycommon
          sudo apt install -y python$PYTHON_VERSION-catkin-tools
          python$PYTHON_VERSION -m pip install --upgrade pip
          python3 -m pip install --upgrade pip
     # - name: Create workspace
      #  run: |
        #  cd src
         # wstool init
          #cd ..
          #rosdep update
          #rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
          
      - name: Build workspace
        if: contains(matrix.container.image, 'noetic') || contains(matrix.container.image, 'noetic')
        run: |
          . /opt/ros/$ROS_DISTRO/setup.bash
          catkin_make
      - name: Unit tests
        run: |
          sudo apt install -y lcov
          . /opt/ros/$ROS_DISTRO/setup.bash
          catkin config --cmake-args -DCMAKE_CXX_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_C_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-lgcov"
          catkin_make tests
          catkin_make run_tests the_rostest
           
  # Run CMake to setup compilation flags
      - name: Configure Coverage CMake 
        run: cmake -D COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -B ${{github.workspace}}/build 
      
      # Compile and executables
      - name: Build Coverage
        working-directory: ${{github.workspace}}/build
        run: make

      # Run test suite and compute code coverage
      - name: Run Test Coverage
        working-directory: ${{github.workspace}}/build
        run: make code_coverage
      
      # Upload coverage result to Coverage.io 
      - name: Upload result to Coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{github.workspace}}/build/coverage.info.cleaned
